#!/bin/bash
#PBS -N delphi_preprocess
#PBS -l select=1:ncpus=8:mem=120gb
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o /rds/general/project/hda_24-25/live/amk125_thesis/logs/delphi_preprocess.log

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate r413

echo "Starting Delphi preprocessing at $(date)"

Rscript /rds/general/project/hda_24-25/live/amk125_thesis/scripts/delphi_preprocess.R

echo "Preprocessing done at $(date)"
